# -*- coding: utf-8 -*-
"""Extrair info site  atv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t81nYLSBNRBTihzOgIsws2FkynR_aF3k
"""

import requests

from bs4 import BeautifulSoup

url = 'https://padrepauloricardo.org/'

headers = {
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'
}
response = requests.get(url, headers=headers)

response.status_code

sp = BeautifulSoup(response.text, 'html.parser')

title = sp.find('title').text
title

headings = sp.find_all(class_='featured-news')

headings

# headings[3]
sabia = headings[0]

type(sabia)

contents = sp.find_all(class_='article')[0]

type(contents)

paragrafos = contents.find_all('p')
links = contents.find_all('a', class_='article__title')

constLink = 'padrepauloricardo.org/'

for a in links:
    title = a.text
    href = constLink + a['href']  # Obtém o link do atributo href



print(title)
for p in paragrafos:
  paragrafo = p.text + '\n'


print(paragrafo)
print("O link para o artigo é: " + href)

"""Formatar email"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

smtp_server = 'smtp.gmail.com'
smtp_port = 587
sender_email = 'meail que envia o cod'
sender_password = 'aq estava a senha de app do email'

# Configurações do e-mail
recipient_emails = ['victor_silva@edu.unifil.br','mario.adaniya@unifil.br' ]
email_subject = 'DS101'

# URL do site a ser extraído
url = 'https://padrepauloricardo.org/'


# Formatar e-mail
email_body = f"<a href='{href}'><h2>{title}</h2></a><br><br>{paragrafo}<p>By: Victor Hugo Macedo Silva (victor_silva@edu.unifil.br)</p>"

# Configuração do e-mail MIME
msg = MIMEMultipart()
msg['From'] = sender_email
msg['To'] = recipient_email
msg['Subject'] = email_subject

# Adicionar corpo do e-mail
msg.attach(MIMEText(email_body, 'html'))

# Iniciar conexão SMTP
server = smtplib.SMTP(smtp_server, smtp_port)
server.starttls()

# Fazer login no servidor SMTP
server.login(sender_email, sender_password)

# Enviar e-mail para cada destinatário
for recipient_email in recipient_emails:
    # Atualizar o destinatário no cabeçalho do e-mail
    msg.replace_header('To', recipient_email)

    # Enviar e-mail
    server.sendmail(sender_email, recipient_email, msg.as_string())

# Encerrar conexão SMTP
server.quit()

print("E-mail enviado com sucesso!")

